/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menustrip_lib;

import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;

/**
 *
 * @author T
 */
public class MenuItem extends javax.swing.JPanel {
    public MenuItem(){
        initComponents();
        initialise("", null);
    }
    
    public MenuItem(String text){
        initComponents();
        initialise(text, null);
    }
    
    public MenuItem(BufferedImage image){
        initComponents();
        initialise("", image);
    }
    
    public MenuItem(String text, BufferedImage image){
        initComponents();
        initialise(text, image);
        
    }
    
    private void initialise(String text, BufferedImage image){
        this.jLabel1.setText(text);
        this.imagePanel1.setImage(image);
    }

    @Override
    public void setFont(Font font){
        super.setFont(font);
        if (this.jLabel1 != null)
            this.jLabel1.setFont(font);
    }
    
    @Override
    public void setForeground(Color c){
        super.setForeground(c);
        if (this.jLabel1 != null)
            this.jLabel1.setForeground(c);
    }
    
    public void setImage(BufferedImage image){
        this.imagePanel1.setImage(image);
    }
    
    
    public void setText(String text){
        this.jLabel1.setText(text);
    }


    public String getText() {
        return this.jLabel1.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagePanel1 = new menustrip_lib.ImagePanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(32767, 40));
        setMinimumSize(new java.awt.Dimension(0, 10));
        setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Text");
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 10));

        imagePanel1.setFocusable(false);
        imagePanel1.setMaximumSize(new java.awt.Dimension(40, 40));
        imagePanel1.setMinimumSize(new java.awt.Dimension(28, 28));
        imagePanel1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menustrip_lib.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
