/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menustrip_lib;

import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author T
 */
public class MenuStrip extends javax.swing.JPanel {
    
    private final String[] menuTitles = new String[]{"New Mail", "Routes", "Carriers", "Review"};
    private final Font font = new Font("tahoma", Font.BOLD, 10);
    
    /**
     * Creates new form MenuStrip
     */
    public MenuStrip() {
        initComponents();
        initialise();
    }
    
    
    
    private void initialise(){
        Color fontColour = Color.WHITE;
        
   

        setMenuItem(this.menuItem1, menuTitles[0], "/resources/newmailicon.png");
        setMenuItem(this.menuItem2, menuTitles[1], "/resources/routesicon.png");
        setMenuItem(this.menuItem3, menuTitles[2], "/resources/newmailicon.png");
        setMenuItem(this.menuItem4, menuTitles[3], "/resources/newmailicon.png");
        setMenuItem(this.menuItem5, "Logout", "/resources/newmailicon.png");
    }
    
        
     
    
    private void setMenuItem(MenuItem item, String text, String imageFile){
        item.setText(text);
        item.setFont(font);
        
        
        /*try{
            BufferedImage image = ImageIO.read(getClass().getResource(imageFile));
            item.setImage(image);
        }catch(IOException e){}*/
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuItem1 = new menustrip_lib.MenuItem();
        menuItem2 = new menustrip_lib.MenuItem();
        menuItem3 = new menustrip_lib.MenuItem();
        menuItem4 = new menustrip_lib.MenuItem();
        menuItem5 = new menustrip_lib.MenuItem();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(0, 49));

        menuItem1.setBackground(new java.awt.Color(102, 102, 102));
        menuItem1.setForeground(new java.awt.Color(255, 255, 255));
        menuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuItem1.setMinimumSize(new java.awt.Dimension(153, 40));

        menuItem2.setBackground(new java.awt.Color(102, 102, 102));
        menuItem2.setForeground(new java.awt.Color(255, 255, 255));
        menuItem2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuItem2.setMinimumSize(new java.awt.Dimension(153, 40));

        menuItem3.setBackground(new java.awt.Color(102, 102, 102));
        menuItem3.setForeground(new java.awt.Color(255, 255, 255));
        menuItem3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuItem3.setMinimumSize(new java.awt.Dimension(153, 40));

        menuItem4.setBackground(new java.awt.Color(102, 102, 102));
        menuItem4.setForeground(new java.awt.Color(255, 255, 255));
        menuItem4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuItem4.setMinimumSize(new java.awt.Dimension(153, 40));

        menuItem5.setBackground(new java.awt.Color(102, 102, 102));
        menuItem5.setForeground(new java.awt.Color(255, 255, 255));
        menuItem5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuItem5.setMinimumSize(new java.awt.Dimension(153, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addComponent(menuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private menustrip_lib.MenuItem menuItem1;
    private menustrip_lib.MenuItem menuItem2;
    private menustrip_lib.MenuItem menuItem3;
    private menustrip_lib.MenuItem menuItem4;
    private menustrip_lib.MenuItem menuItem5;
    // End of variables declaration//GEN-END:variables
}
